services:
  - type: web
    name: springboot-backend
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://db4free.net:3306/your_db_name
      - key: SPRING_DATASOURCE_USERNAME
        value: your_db_username
      - key: SPRING_DATASOURCE_PASSWORD
        value: your_db_password
