services:
  - type: web
    name: springboot-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://db4free.net:3306/food_db01
      - key: SPRING_DATASOURCE_USERNAME
        value: arul1234
      - key: SPRING_DATASOURCE_PASSWORD
        value: Arul2005
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: true
