services:
  - type: web
    name: springboot-backend
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12784322
      - key: SPRING_DATASOURCE_USERNAME
        value: sql12784322
      - key: SPRING_DATASOURCE_PASSWORD
        value: PfK3JJxBaG
