services:
  - type: web
    name: springboot-backend
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://db4free.net:3306/food_db01
      - key: SPRING_DATASOURCE_USERNAME
        value: arul1234
      - key: SPRING_DATASOURCE_PASSWORD
        value: Arul@2005
